apiVersion: v1
kind: Service
metadata:
  name: gpt2-k8s-service
spec:
  type: NodePort
  selector:
    app: gpt2-k8s
  ports:
    - port: 6006         # 服务端口
      targetPort: 6006   # 容器端口
      nodePort: 30066    # 本地访问端口（可改）
